version: '3.1'

services:
  gen_avatar:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:4010
    restart: always

networks:
  default:
    external: true
    name: scoobydoo